### ISSUE TITLE
Add `Copy To Clipboard` to `pre` elements

### ISSUE THREAD

**Issue by Cahllagerfeld** [ghostdevv/gitpodify#1]
Making it easier to copy the generated code, by adding a `Copy To Clipboard` functionality.

Designwise, when not wanting to use an icon, a solution would be to initially display a button with the text `copy`. When clicking on it turn the text to `copied to clipboard`, and after a given time switch back to the initial state.

If not relevant, feel free to close that issue :)

**Comment by Siddhant-K-code** [comment]
On it.
Will make a PR for that.

**Comment by jacobparis** [comment]
@Cahllagerfeld Great idea, this is fixed in #3
